// Package main — standalone MikroTik monitoring dashboard (InfluxDB v3).
//
// Connects to MikroTik, streams monitoring data to Redis Pub/Sub (live SSE)
// and InfluxDB v3 (historical SQL queries). Serves dashboard at :9090.
//
// First-time setup:
//
//	docker compose -f deployments/docker-compose.monitor.yml up -d
//	docker exec influxdb3-core influxdb3 create token --admin  # save the token
//	docker exec influxdb3-core influxdb3 create database mikrotik
//
// Then set INFLUX_TOKEN env var and run:
//
//	INFLUX_TOKEN=<token> go run ./cmd/mikrotik
//	# or just update the influxToken const below
package main

import (
	"context"
	"embed"
	"encoding/json"
	"fmt"
	"io/fs"
	"log"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	influxdb3 "github.com/InfluxCommunity/influxdb3-go/v2/influxdb3"
	"github.com/redis/go-redis/v9"

	"github.com/Butterfly-Student/go-ros/client"
	"mikmongo/internal/collector/parse"
)

//go:embed static
var staticFiles embed.FS

// ─────────────────────────────────────────────────────────────────────────────
// Config
// ─────────────────────────────────────────────────────────────────────────────

const (
	routerHost = "192.168.233.1"
	routerPort = 8728
	routerUser = "admin"
	routerPass = "r00t"

	redisAddr  = "localhost:6380"
	redisChan  = "monitor:live"

	influxURL      = "http://localhost:8181" // v3 default port
	influxDatabase = "mikrotik"
	httpAddr       = ":9090"
)

// influxToken reads from env INFLUX_TOKEN, fallback to hardcoded local dev token.
func influxToken() string {
	if t := os.Getenv("INFLUX_TOKEN"); t != "" {
		return t
	}
	// Token generated by: docker exec influxdb3-core influxdb3 create token --admin
	return "apiv3_Rhcm1B5OX-m5ZtS24Z8yTI8AHFV7Jc1nsYn_g1aZc8cj3tAS1G5gqFRwlqKqmqVMkb94k9Wepd5xduvZpH2OFQ"
}

// ─────────────────────────────────────────────────────────────────────────────
// Live event payload
// ─────────────────────────────────────────────────────────────────────────────

type liveEvent struct {
	Timestamp string            `json:"ts"`
	Topic     string            `json:"topic"`
	Fields    map[string]string `json:"fields"`
}

// ─────────────────────────────────────────────────────────────────────────────
// main
// ─────────────────────────────────────────────────────────────────────────────

func main() {
	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()

	// ── Redis ──────────────────────────────────────────────────────────────────
	rdb := redis.NewClient(&redis.Options{Addr: redisAddr})
	if err := rdb.Ping(ctx).Err(); err != nil {
		log.Fatalf("redis connect (%s): %v", redisAddr, err)
	}
	log.Printf("✓ Redis        %s", redisAddr)

	// ── InfluxDB v3 ────────────────────────────────────────────────────────────
	influx, err := influxdb3.New(influxdb3.ClientConfig{
		Host:     influxURL,
		Token:    influxToken(),
		Database: influxDatabase,
	})
	if err != nil {
		log.Fatalf("influxdb3 client: %v", err)
	}
	defer influx.Close()
	log.Printf("✓ InfluxDB v3  %s  database=%s", influxURL, influxDatabase)

	// ── MikroTik ───────────────────────────────────────────────────────────────
	cfg := client.Config{
		Host:     routerHost,
		Port:     routerPort,
		Username: routerUser,
		Password: routerPass,
		Timeout:  10 * time.Second,
	}
	mikClient, err := client.New(cfg)
	if err != nil {
		log.Fatalf("mikrotik connect (%s:%d): %v", routerHost, routerPort, err)
	}
	defer mikClient.Close()
	log.Printf("✓ MikroTik     %s:%d  user=%s", routerHost, routerPort, routerUser)

	// ── Streaming ──────────────────────────────────────────────────────────────
	go runStream(ctx, mikClient, rdb, influx)

	// ── HTTP server ────────────────────────────────────────────────────────────
	mux := http.NewServeMux()
	mux.HandleFunc("/api/live", sseHandler(rdb))
	mux.HandleFunc("/api/history", historyHandler(influx))
	mux.HandleFunc("/api/interfaces", listHandler(mikClient, "/interface/print", "=.proplist=name,type,running,disabled"))
	mux.HandleFunc("/api/queues", listHandler(mikClient, "/queue/simple/print", "=.proplist=name,target"))
	mux.Handle("/", staticHandler())

	srv := &http.Server{Addr: httpAddr, Handler: mux}
	go func() {
		log.Printf("✓ Dashboard    http://localhost%s", httpAddr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("http: %v", err)
		}
	}()

	<-ctx.Done()
	log.Println("Shutting down…")
	shutCtx, sc := context.WithTimeout(context.Background(), 5*time.Second)
	defer sc()
	_ = srv.Shutdown(shutCtx)
	log.Println("Done.")
}

// ─────────────────────────────────────────────────────────────────────────────
// Streaming loop
// ─────────────────────────────────────────────────────────────────────────────

func runStream(
	ctx context.Context,
	mikClient *client.Client,
	rdb *redis.Client,
	influx *influxdb3.Client,
) {
	commands := monitorCommands()
	args := make([][]string, len(commands))
	for i, c := range commands {
		args[i] = c.args
	}

	delay := 2 * time.Second
	for {
		if ctx.Err() != nil {
			return
		}

		ch, err := mikClient.ListenManyArgsContext(ctx, args, 256)
		if err != nil {
			log.Printf("stream start error: %v — retry in %v", err, delay)
			select {
			case <-ctx.Done():
				return
			case <-time.After(delay):
			}
			if delay < 30*time.Second {
				delay *= 2
			}
			continue
		}
		delay = 2 * time.Second
		log.Printf("Streaming %d commands…", len(commands))

		for ev := range ch {
			if ev.Err != nil {
				log.Printf("event error [%d]: %v", ev.Index, ev.Err)
				continue
			}
			cmd := commands[ev.Index]
			now := time.Now()

			// Publish to Redis → SSE
			payload, _ := json.Marshal(liveEvent{
				Timestamp: now.Format(time.RFC3339Nano),
				Topic:     cmd.topic,
				Fields:    ev.Map,
			})
			rdb.Publish(ctx, redisChan, payload)

			// Cache latest in Redis HSET (60s TTL)
			key := "monitor:cache:" + cmd.topic
			hf := make(map[string]interface{}, len(ev.Map)+1)
			for k, v := range ev.Map {
				hf[k] = v
			}
			hf["_ts"] = now.Unix()
			rdb.HSet(ctx, key, hf)
			rdb.Expire(ctx, key, 60*time.Second)

			// Write numeric fields to InfluxDB v3
			p := parse.ForTopic(cmd.topic)
			tags, fields := p.Parse(ev.Map)
			if len(fields) > 0 {
				pt := influxdb3.NewPointWithMeasurement(cmd.topic)
				pt.SetTimestamp(now)
				pt.SetTag("host", routerHost)
				for k, v := range tags {
					pt.SetTag(k, v)
				}
				for k, v := range fields {
					pt.SetField(k, v)
				}
				if err := influx.WritePoints(ctx, []*influxdb3.Point{pt}); err != nil {
					log.Printf("influx write [%s]: %v", cmd.topic, err)
				}
			}
		}

		if ctx.Err() != nil {
			return
		}
		log.Printf("Stream closed, reconnecting in %v…", delay)
		select {
		case <-ctx.Done():
			return
		case <-time.After(delay):
		}
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// HTTP handlers
// ─────────────────────────────────────────────────────────────────────────────

// sseHandler subscribes to Redis Pub/Sub → streams to browser via SSE.
func sseHandler(rdb *redis.Client) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		fl, ok := w.(http.Flusher)
		if !ok {
			http.Error(w, "streaming not supported", 500)
			return
		}
		w.Header().Set("Content-Type", "text/event-stream")
		w.Header().Set("Cache-Control", "no-cache")
		w.Header().Set("Connection", "keep-alive")
		w.Header().Set("Access-Control-Allow-Origin", "*")

		sub := rdb.Subscribe(r.Context(), redisChan)
		defer sub.Close()

		for {
			select {
			case <-r.Context().Done():
				return
			case msg, ok := <-sub.Channel():
				if !ok {
					return
				}
				fmt.Fprintf(w, "data: %s\n\n", msg.Payload)
				fl.Flush()
			}
		}
	}
}

// historyHandler queries InfluxDB v3 via SQL and returns JSON.
//
// Query params:
//
//	topic    — measurement name (default: system-resource)
//	duration — lookback window  (default: 15m)  e.g. 1h, 6h, 24h
//	name     — optional tag filter for interface or queue name
func historyHandler(influx *influxdb3.Client) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Content-Type", "application/json")

		topic := r.URL.Query().Get("topic")
		if topic == "" {
			topic = "system-resource"
		}
		duration := r.URL.Query().Get("duration")
		if duration == "" {
			duration = "15m"
		}
		nameFilter := r.URL.Query().Get("name")

		// Sanitise inputs (only allow alphanumeric, dash, underscore)
		topic = sanitise(topic)
		duration = sanitise(duration)
		nameFilter = sanitise(nameFilter)

		// Build SQL WHERE clause
		whereClause := fmt.Sprintf(`WHERE time >= now() - interval '%s'`, durationToInterval(duration))
		if nameFilter != "" {
			whereClause += fmt.Sprintf(` AND "name" = '%s'`, nameFilter)
		}

		sql := fmt.Sprintf(
			`SELECT * FROM "%s" %s ORDER BY time`,
			topic, whereClause,
		)

		iter, err := influx.Query(r.Context(), sql)
		if err != nil {
			http.Error(w, fmt.Sprintf(`{"error":%q}`, err.Error()), 500)
			return
		}
		defer iter.Done()

		type row = map[string]interface{}
		var rows []row

		for iter.Next() {
			rec := iter.Value()
			r2 := make(row, len(rec))
			for k, v := range rec {
				// Convert time column to RFC3339 string
				if k == "time" {
					if t, ok := v.(time.Time); ok {
						r2["time"] = t.Format(time.RFC3339)
						continue
					}
				}
				// Skip internal InfluxDB columns
				if strings.HasPrefix(k, "iox::") {
					continue
				}
				r2[k] = v
			}
			rows = append(rows, r2)
		}
		if err := iter.Err(); err != nil {
			http.Error(w, fmt.Sprintf(`{"error":%q}`, err.Error()), 500)
			return
		}

		if rows == nil {
			rows = []row{}
		}
		json.NewEncoder(w).Encode(rows)
	}
}

// listHandler runs a one-shot RouterOS command and returns result as JSON.
func listHandler(mikClient *client.Client, path string, args ...string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Content-Type", "application/json")
		cmdArgs := append([]string{path}, args...)
		reply, err := mikClient.RunArgsContext(r.Context(), cmdArgs)
		if err != nil {
			http.Error(w, fmt.Sprintf(`{"error":%q}`, err.Error()), 500)
			return
		}
		rows := make([]map[string]string, 0, len(reply.Re))
		for _, re := range reply.Re {
			rows = append(rows, re.Map)
		}
		json.NewEncoder(w).Encode(rows)
	}
}

// staticHandler serves the embedded static/ directory.
func staticHandler() http.Handler {
	sub, err := fs.Sub(staticFiles, "static")
	if err != nil {
		log.Fatalf("embed static sub: %v", err)
	}
	return http.FileServer(http.FS(sub))
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

// durationToInterval converts "15m", "1h", "6h", "24h" → SQL interval string.
func durationToInterval(d string) string {
	switch d {
	case "5m":
		return "5 minutes"
	case "10m":
		return "10 minutes"
	case "15m":
		return "15 minutes"
	case "30m":
		return "30 minutes"
	case "1h":
		return "1 hour"
	case "6h":
		return "6 hours"
	case "24h":
		return "24 hours"
	default:
		return "15 minutes"
	}
}

// sanitise keeps only alphanumeric characters, dash, underscore, and dot.
// Used to prevent SQL injection in query parameters.
func sanitise(s string) string {
	var b strings.Builder
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') ||
			(r >= '0' && r <= '9') || r == '-' || r == '_' || r == '.' {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// ─────────────────────────────────────────────────────────────────────────────
// Monitor commands
// ─────────────────────────────────────────────────────────────────────────────

type monitorCmd struct {
	args  []string
	topic string
}

func monitorCommands() []monitorCmd {
	return []monitorCmd{
		{
			topic: "system-resource",
			args: []string{
				"/system/resource/print",
				"=interval=2",
			},
		},
		{
			topic: "interface-traffic",
			args: []string{
				"/interface/monitor-traffic",
				"=interface=ether1",
				"=interval=1",
			},
		},
		{
			topic: "queue-stats",
			args: []string{
				"/queue/simple/print",
				"=stats=",
				"=interval=1",
			},
		},
		{
			topic: "ip-addresses",
			args: []string{
				"/ip/address/print",
				"=.proplist=.id,address,interface,network,disabled",
				"=follow=",
			},
		},
		{
			topic: "ppp-active",
			args: []string{
				"/ppp/active/print",
				"=.proplist=.id,name,service,address,uptime,caller-id",
				"=follow=",
			},
		},
		{
			topic: "dhcp-leases",
			args: []string{
				"/ip/dhcp-server/lease/print",
				"=.proplist=.id,address,mac-address,host-name,status,server",
				"=follow=",
			},
		},
		{
			topic: "router-log",
			args: []string{
				"/log/print",
				"=.proplist=.id,topics,severity,message,time",
				"=follow=",
			},
		},
	}
}
