// src/main.tsx
// Application entrypoint — wires QueryClient + Router + auth context.
// Auth context hooks (useAdminAuthContext, etc.) are stubs here;
// Plan 01-02 fills them with real Zustand selectors.
import React from "react"
import ReactDOM from "react-dom/client"
import { RouterProvider, createRouter } from "@tanstack/react-router"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"
import { Toaster } from "sonner"

// Route tree generated by TanStack Router Vite plugin
import { routeTree } from "./routeTree.gen"

// Global styles (Tailwind v4 + Shadcn/UI CSS variables)
import "./styles/globals.css"

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1000 * 60 * 5,   // 5 minutes
      gcTime: 1000 * 60 * 10,      // 10 minutes
      retry: 2,
      refetchOnWindowFocus: false,
    },
  },
})

const router = createRouter({
  routeTree,
  context: {
    // Stub context — Plan 01-02 replaces undefined! with real auth selectors
    adminAuth: { isAuthenticated: false, role: null, accessToken: null },
    agentAuth: { isAuthenticated: false, accessToken: null },
    customerAuth: { isAuthenticated: false, accessToken: null },
    queryClient,
  },
})

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router
  }
}

function App() {
  return (
    <>
      <RouterProvider router={router} />
      <Toaster position="top-right" richColors />
      {import.meta.env.DEV && <ReactQueryDevtools initialIsOpen={false} />}
    </>
  )
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <App />
    </QueryClientProvider>
  </React.StrictMode>
)
