/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerLoginRouteImport } from './routes/customer/login'
import { Route as AgentLoginRouteImport } from './routes/agent/login'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as CustomerCustomerAuthRouteRouteImport } from './routes/customer/_customerAuth/route'
import { Route as AgentAgentAuthRouteRouteImport } from './routes/agent/_agentAuth/route'
import { Route as CustomerCustomerAuthDashboardRouteImport } from './routes/customer/_customerAuth/dashboard'
import { Route as AgentAgentAuthDashboardRouteImport } from './routes/agent/_agentAuth/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer/login',
  path: '/customer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLoginRoute = AgentLoginRouteImport.update({
  id: '/agent/login',
  path: '/agent/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CustomerCustomerAuthRouteRoute =
  CustomerCustomerAuthRouteRouteImport.update({
    id: '/customer/_customerAuth',
    path: '/customer',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentAgentAuthRouteRoute = AgentAgentAuthRouteRouteImport.update({
  id: '/agent/_agentAuth',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCustomerAuthDashboardRoute =
  CustomerCustomerAuthDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => CustomerCustomerAuthRouteRoute,
  } as any)
const AgentAgentAuthDashboardRoute = AgentAgentAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AgentAgentAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agent': typeof AgentAgentAuthRouteRouteWithChildren
  '/customer': typeof CustomerCustomerAuthRouteRouteWithChildren
  '/dashboard': typeof AdminDashboardRoute
  '/agent/login': typeof AgentLoginRoute
  '/customer/login': typeof CustomerLoginRoute
  '/agent/dashboard': typeof AgentAgentAuthDashboardRoute
  '/customer/dashboard': typeof CustomerCustomerAuthDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agent': typeof AgentAgentAuthRouteRouteWithChildren
  '/customer': typeof CustomerCustomerAuthRouteRouteWithChildren
  '/dashboard': typeof AdminDashboardRoute
  '/agent/login': typeof AgentLoginRoute
  '/customer/login': typeof CustomerLoginRoute
  '/agent/dashboard': typeof AgentAgentAuthDashboardRoute
  '/customer/dashboard': typeof CustomerCustomerAuthDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/agent/_agentAuth': typeof AgentAgentAuthRouteRouteWithChildren
  '/customer/_customerAuth': typeof CustomerCustomerAuthRouteRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/agent/login': typeof AgentLoginRoute
  '/customer/login': typeof CustomerLoginRoute
  '/agent/_agentAuth/dashboard': typeof AgentAgentAuthDashboardRoute
  '/customer/_customerAuth/dashboard': typeof CustomerCustomerAuthDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agent'
    | '/customer'
    | '/dashboard'
    | '/agent/login'
    | '/customer/login'
    | '/agent/dashboard'
    | '/customer/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agent'
    | '/customer'
    | '/dashboard'
    | '/agent/login'
    | '/customer/login'
    | '/agent/dashboard'
    | '/customer/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/agent/_agentAuth'
    | '/customer/_customerAuth'
    | '/_admin/dashboard'
    | '/agent/login'
    | '/customer/login'
    | '/agent/_agentAuth/dashboard'
    | '/customer/_customerAuth/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AgentAgentAuthRouteRoute: typeof AgentAgentAuthRouteRouteWithChildren
  CustomerCustomerAuthRouteRoute: typeof CustomerCustomerAuthRouteRouteWithChildren
  AgentLoginRoute: typeof AgentLoginRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/customer/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/login': {
      id: '/agent/login'
      path: '/agent/login'
      fullPath: '/agent/login'
      preLoaderRoute: typeof AgentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/customer/_customerAuth': {
      id: '/customer/_customerAuth'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerCustomerAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/_agentAuth': {
      id: '/agent/_agentAuth'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentAgentAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/_customerAuth/dashboard': {
      id: '/customer/_customerAuth/dashboard'
      path: '/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerCustomerAuthDashboardRouteImport
      parentRoute: typeof CustomerCustomerAuthRouteRoute
    }
    '/agent/_agentAuth/dashboard': {
      id: '/agent/_agentAuth/dashboard'
      path: '/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AgentAgentAuthDashboardRouteImport
      parentRoute: typeof AgentAgentAuthRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AgentAgentAuthRouteRouteChildren {
  AgentAgentAuthDashboardRoute: typeof AgentAgentAuthDashboardRoute
}

const AgentAgentAuthRouteRouteChildren: AgentAgentAuthRouteRouteChildren = {
  AgentAgentAuthDashboardRoute: AgentAgentAuthDashboardRoute,
}

const AgentAgentAuthRouteRouteWithChildren =
  AgentAgentAuthRouteRoute._addFileChildren(AgentAgentAuthRouteRouteChildren)

interface CustomerCustomerAuthRouteRouteChildren {
  CustomerCustomerAuthDashboardRoute: typeof CustomerCustomerAuthDashboardRoute
}

const CustomerCustomerAuthRouteRouteChildren: CustomerCustomerAuthRouteRouteChildren =
  {
    CustomerCustomerAuthDashboardRoute: CustomerCustomerAuthDashboardRoute,
  }

const CustomerCustomerAuthRouteRouteWithChildren =
  CustomerCustomerAuthRouteRoute._addFileChildren(
    CustomerCustomerAuthRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AgentAgentAuthRouteRoute: AgentAgentAuthRouteRouteWithChildren,
  CustomerCustomerAuthRouteRoute: CustomerCustomerAuthRouteRouteWithChildren,
  AgentLoginRoute: AgentLoginRoute,
  CustomerLoginRoute: CustomerLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
