package model

import (
	"time"

	"gorm.io/gorm"
)

// Invoice represents customer billing invoices
type Invoice struct {
	ID                 string         `gorm:"type:uuid;primary_key;default:gen_random_uuid()" json:"id"`
	InvoiceNumber      string         `gorm:"type:varchar(50);unique;not null;index" json:"invoice_number"`
	CustomerID         string         `gorm:"type:uuid;not null;index:,where:deleted_at IS NULL" json:"customer_id"`
	SubscriptionID     *string        `gorm:"type:uuid;index:,where:subscription_id IS NOT NULL AND deleted_at IS NULL" json:"subscription_id"`
	BillingPeriodStart time.Time      `gorm:"type:date;not null" json:"billing_period_start"`
	BillingPeriodEnd   time.Time      `gorm:"type:date;not null" json:"billing_period_end"`
	BillingMonth       *int           `gorm:"type:integer;check:billing_month BETWEEN 1 AND 12" json:"billing_month"`
	BillingYear        *int           `gorm:"type:integer" json:"billing_year"`
	IssueDate          time.Time      `gorm:"type:date;not null;default:CURRENT_DATE" json:"issue_date"`
	DueDate            time.Time      `gorm:"type:date;not null;index:,where:deleted_at IS NULL" json:"due_date"`
	PaymentDeadline    *time.Time     `gorm:"type:timestamptz" json:"payment_deadline"`
	Subtotal           float64        `gorm:"type:decimal(12,2);not null;default:0" json:"subtotal"`
	TaxAmount          float64        `gorm:"type:decimal(12,2);not null;default:0" json:"tax_amount"`
	DiscountAmount     float64        `gorm:"type:decimal(12,2);default:0" json:"discount_amount"`
	LateFee            float64        `gorm:"type:decimal(12,2);default:0" json:"late_fee"`
	TotalAmount        float64        `gorm:"type:decimal(12,2);not null" json:"total_amount"`
	PaidAmount         float64        `gorm:"type:decimal(12,2);default:0" json:"paid_amount"`
	Balance            float64        `gorm:"type:decimal(12,2);->" json:"balance"`
	Status             string         `gorm:"type:varchar(20);not null;default:'draft';check:status IN ('draft','sent','unpaid','partial','paid','overpaid','overdue','cancelled','refunded');index:,where:deleted_at IS NULL" json:"status"`
	PaymentDate        *time.Time     `gorm:"type:timestamptz" json:"payment_date"`
	PaymentMethod      *string        `gorm:"type:varchar(20)" json:"payment_method"`
	InvoiceType        string         `gorm:"type:varchar(20);default:'recurring';check:invoice_type IN ('recurring', 'installation', 'additional', 'refund')" json:"invoice_type"`
	IsAutoGenerated    bool           `gorm:"type:boolean;default:true" json:"is_auto_generated"`
	ReminderSentCount  int            `gorm:"type:integer;default:0" json:"reminder_sent_count"`
	LastReminderSent   *time.Time     `gorm:"type:timestamptz" json:"last_reminder_sent"`
	Notes              *string        `gorm:"type:text" json:"notes"`
	InternalNotes      *string        `gorm:"type:text" json:"internal_notes"`
	CreatedBy          *string        `gorm:"type:uuid" json:"created_by"`
	UpdatedBy          *string        `gorm:"type:uuid" json:"updated_by"`
	CreatedAt          time.Time      `gorm:"type:timestamptz;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt          time.Time      `gorm:"type:timestamptz;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt          gorm.DeletedAt `gorm:"index" json:"-"`

	// Relationships
	Customer           Customer            `gorm:"foreignKey:CustomerID" json:"customer,omitempty"`
	Subscription       *Subscription       `gorm:"foreignKey:SubscriptionID" json:"subscription,omitempty"`
	Creator            *User               `gorm:"foreignKey:CreatedBy" json:"-"`
	Updater            *User               `gorm:"foreignKey:UpdatedBy" json:"-"`
	InvoiceItems       []InvoiceItem       `gorm:"foreignKey:InvoiceID" json:"invoice_items,omitempty"`
	PaymentAllocations []PaymentAllocation `gorm:"foreignKey:InvoiceID" json:"payment_allocations,omitempty"`
}

func (Invoice) TableName() string {
	return "invoices"
}
