package model

import (
	"time"

	"gorm.io/gorm"
)

// Invoice represents customer billing invoices
type Invoice struct {
	ID                 string         `gorm:"type:uuid;primary_key;default:gen_random_uuid()"`
	InvoiceNumber      string         `gorm:"type:varchar(50);unique;not null;index"`
	CustomerID         string         `gorm:"type:uuid;not null;index:,where:deleted_at IS NULL"`
	SubscriptionID     *string        `gorm:"type:uuid;index:,where:subscription_id IS NOT NULL AND deleted_at IS NULL"`
	BillingPeriodStart time.Time      `gorm:"type:date;not null"`
	BillingPeriodEnd   time.Time      `gorm:"type:date;not null"`
	BillingMonth       *int           `gorm:"type:integer;check:billing_month BETWEEN 1 AND 12"`
	BillingYear        *int           `gorm:"type:integer"`
	IssueDate          time.Time      `gorm:"type:date;not null;default:CURRENT_DATE"`
	DueDate            time.Time      `gorm:"type:date;not null;index:,where:deleted_at IS NULL"`
	PaymentDeadline    *time.Time     `gorm:"type:timestamptz"`
	Subtotal           float64        `gorm:"type:decimal(12,2);not null;default:0"`
	TaxAmount          float64        `gorm:"type:decimal(12,2);not null;default:0"`
	DiscountAmount     float64        `gorm:"type:decimal(12,2);default:0"`
	LateFee            float64        `gorm:"type:decimal(12,2);default:0"`
	TotalAmount        float64        `gorm:"type:decimal(12,2);not null"`
	PaidAmount         float64        `gorm:"type:decimal(12,2);default:0"`
	Balance            float64        `gorm:"type:decimal(12,2);->"`
	Status             string         `gorm:"type:varchar(20);not null;default:'draft';check:status IN ('draft','sent','unpaid','partial','paid','overpaid','overdue','cancelled','refunded');index:,where:deleted_at IS NULL"`
	PaymentDate        *time.Time     `gorm:"type:timestamptz"`
	PaymentMethod      *string        `gorm:"type:varchar(20)"`
	InvoiceType        string         `gorm:"type:varchar(20);default:'recurring';check:invoice_type IN ('recurring', 'installation', 'additional', 'refund')"`
	IsAutoGenerated    bool           `gorm:"type:boolean;default:true"`
	ReminderSentCount  int            `gorm:"type:integer;default:0"`
	LastReminderSent   *time.Time     `gorm:"type:timestamptz"`
	Notes              *string        `gorm:"type:text"`
	InternalNotes      *string        `gorm:"type:text"`
	CreatedBy          *string        `gorm:"type:uuid"`
	UpdatedBy          *string        `gorm:"type:uuid"`
	CreatedAt          time.Time      `gorm:"type:timestamptz;not null;default:CURRENT_TIMESTAMP"`
	UpdatedAt          time.Time      `gorm:"type:timestamptz;not null;default:CURRENT_TIMESTAMP"`
	DeletedAt          gorm.DeletedAt `gorm:"index"`

	// Relationships
	Customer           Customer            `gorm:"foreignKey:CustomerID"`
	Subscription       *Subscription       `gorm:"foreignKey:SubscriptionID"`
	Creator            *User               `gorm:"foreignKey:CreatedBy"`
	Updater            *User               `gorm:"foreignKey:UpdatedBy"`
	InvoiceItems       []InvoiceItem       `gorm:"foreignKey:InvoiceID"`
	PaymentAllocations []PaymentAllocation `gorm:"foreignKey:InvoiceID"`
}

func (Invoice) TableName() string {
	return "invoices"
}
