//go:build integration

package integration

import (
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.uber.org/zap"
	"mikmongo/internal/domain"
	"mikmongo/internal/model"
	"mikmongo/internal/repository/postgres"
	"mikmongo/internal/service"
)

// billingTestSetup creates router+profile+customer+subscription in DB
// without connecting to a real MikroTik device.
func billingTestSetup(
	t *testing.T, suite *TestSuite, repos *postgres.Registry,
	customerName, phone, profileCode string, priceMonthly float64, taxRate float64,
	billingDay *int,
) (*model.Customer, *model.Subscription, *model.BandwidthProfile) {
	t.Helper()

	logger := zap.NewNop()
	routerSvc := service.NewRouterService(repos.RouterDeviceRepo, "test-key-16-bytes", nil, logger)
	customerSvc := service.NewCustomerService(repos.CustomerRepo, repos.SequenceCounterRepo, repos.BandwidthProfileRepo, domain.NewCustomerDomain(), routerSvc)

	router := &model.MikrotikRouter{
		ID:                uuid.New().String(),
		Name:              "Router-" + profileCode,
		Address:           "192.168.88.1",
		APIPort:           8728,
		Username:          "admin",
		PasswordEncrypted: "placeholder",
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	}
	require.NoError(t, repos.RouterDeviceRepo.Create(suite.Ctx, router))

	graceDays := 3
	profile := &model.BandwidthProfile{
		ID:              uuid.New().String(),
		RouterID:        router.ID,
		ProfileCode:     profileCode,
		Name:            profileCode + " Profile",
		DownloadSpeed:   10000,
		UploadSpeed:     10000,
		PriceMonthly:    priceMonthly,
		TaxRate:         taxRate,
		GracePeriodDays: graceDays,
		BillingDay:      billingDay,
		IsActive:        true,
		CreatedAt:       time.Now(),
		UpdatedAt:       time.Now(),
	}
	require.NoError(t, repos.BandwidthProfileRepo.Create(suite.Ctx, profile))

	customer := &model.Customer{FullName: customerName, Phone: phone}
	require.NoError(t, customerSvc.Create(suite.Ctx, customer))

	sub := &model.Subscription{
		CustomerID:  customer.ID,
		PlanID:      profile.ID,
		RouterID:    router.ID,
		Username:    "user-" + profileCode,
		Password:    "password123",
		AutoIsolate: true,
	}
	directCreateSub(t, suite, sub)

	return customer, sub, profile
}

func TestBillingLifecycle_GenerateInvoice(t *testing.T) {
	suite := SetupSuite(t)
	defer suite.TearDownSuite(t)
	defer suite.Cleanup(t)

	repos := postgres.NewRepository(suite.DB)
	billingSvc := service.NewBillingService(
		repos.InvoiceRepo, repos.InvoiceItemRepo, repos.SubscriptionRepo,
		repos.BandwidthProfileRepo, repos.CustomerRepo, repos.SystemSettingRepo,
		repos.SequenceCounterRepo, domain.NewBillingDomain(),
	)

	customer, sub, profile := billingTestSetup(t, suite, repos,
		"Billing Test", "081111111111", "TEST10", 200_000, 0.11, nil)

	// Activate directly with activated_at = start of current month (no proration)
	startOfMonth := time.Date(time.Now().Year(), time.Now().Month(), 1, 0, 0, 0, 0, time.Local)
	err := suite.DB.WithContext(suite.Ctx).
		Exec("UPDATE subscriptions SET status='active', activated_at=? WHERE id=?", startOfMonth, sub.ID).Error
	require.NoError(t, err)

	subID, _ := uuid.Parse(sub.ID)
	inv, err := billingSvc.GenerateInvoice(suite.Ctx, subID, time.Now())
	require.NoError(t, err)
	require.NotNil(t, inv)

	assert.Equal(t, customer.ID, inv.CustomerID)
	assert.Equal(t, "unpaid", inv.Status)
	assert.Equal(t, "recurring", inv.InvoiceType)
	assert.True(t, inv.IsAutoGenerated)
	assert.Equal(t, profile.PriceMonthly, inv.Subtotal)
	assert.InDelta(t, 22_000, inv.TaxAmount, 1) // 11% of 200_000
	assert.InDelta(t, 222_000, inv.TotalAmount, 1)
	assert.NotEmpty(t, inv.InvoiceNumber)
}

func TestBillingLifecycle_Proration(t *testing.T) {
	suite := SetupSuite(t)
	defer suite.TearDownSuite(t)
	defer suite.Cleanup(t)

	repos := postgres.NewRepository(suite.DB)
	billingSvc := service.NewBillingService(
		repos.InvoiceRepo, repos.InvoiceItemRepo, repos.SubscriptionRepo,
		repos.BandwidthProfileRepo, repos.CustomerRepo, repos.SystemSettingRepo,
		repos.SequenceCounterRepo, domain.NewBillingDomain(),
	)

	_, sub, profile := billingTestSetup(t, suite, repos,
		"Proration Test", "082222222222", "PRO10", 310_000, 0, nil)

	// Activate on day 16 of March 2024
	activatedAt := time.Date(2024, time.March, 16, 0, 0, 0, 0, time.Local)
	billedPeriod := time.Date(2024, time.March, 1, 0, 0, 0, 0, time.Local)

	sub.ActivatedAt = &activatedAt
	sub.Status = "active"
	require.NoError(t, repos.SubscriptionRepo.Update(suite.Ctx, sub))

	subID, _ := uuid.Parse(sub.ID)
	inv, err := billingSvc.GenerateInvoice(suite.Ctx, subID, billedPeriod)
	require.NoError(t, err)

	// March 2024: 31 days; activated day 16 → billedDays=16 → proration ≈ 160_000
	assert.Less(t, inv.Subtotal, profile.PriceMonthly)
	assert.Greater(t, inv.Subtotal, 0.0)
	assert.InDelta(t, 160_000, inv.Subtotal, 1000)
}

func TestBillingLifecycle_ProcessDailyBilling(t *testing.T) {
	suite := SetupSuite(t)
	defer suite.TearDownSuite(t)
	defer suite.Cleanup(t)

	repos := postgres.NewRepository(suite.DB)
	billingSvc := service.NewBillingService(
		repos.InvoiceRepo, repos.InvoiceItemRepo, repos.SubscriptionRepo,
		repos.BandwidthProfileRepo, repos.CustomerRepo, repos.SystemSettingRepo,
		repos.SequenceCounterRepo, domain.NewBillingDomain(),
	)

	today := time.Now().Day()
	_, sub, _ := billingTestSetup(t, suite, repos,
		"Daily Billing", "083333333333", "DAILY10", 200_000, 0, &today)

	// Activate directly
	directActivate(t, suite, sub.ID)

	err := billingSvc.ProcessDailyBilling(suite.Ctx)
	require.NoError(t, err)

	customerID, _ := uuid.Parse(sub.CustomerID)
	invoices, err := repos.InvoiceRepo.GetByCustomerID(suite.Ctx, customerID)
	require.NoError(t, err)
	assert.NotEmpty(t, invoices, "invoice should have been generated for billing day = today")
}

func TestBillingLifecycle_OverdueIsolation(t *testing.T) {
	suite := SetupSuite(t)
	defer suite.TearDownSuite(t)
	defer suite.Cleanup(t)

	repos := postgres.NewRepository(suite.DB)
	billingSvc := service.NewBillingService(
		repos.InvoiceRepo, repos.InvoiceItemRepo, repos.SubscriptionRepo,
		repos.BandwidthProfileRepo, repos.CustomerRepo, repos.SystemSettingRepo,
		repos.SequenceCounterRepo, domain.NewBillingDomain(),
	)
	// subscriptionSvc intentionally NOT set — Isolate() requires router connection.
	// We verify the billing domain correctly detects the overdue, then simulate isolation.

	_, sub, _ := billingTestSetup(t, suite, repos,
		"Overdue Customer", "084444444444", "OVERDUE10", 200_000, 0, nil)

	directActivate(t, suite, sub.ID)

	// Create overdue invoice (past grace period)
	graceDays := 3
	dueDate := time.Now().AddDate(0, 0, -(graceDays + 5))
	subIDStr := sub.ID
	invoice := &model.Invoice{
		InvoiceNumber:      "INV-OVERDUE-001",
		CustomerID:         sub.CustomerID,
		SubscriptionID:     &subIDStr,
		BillingPeriodStart: dueDate.AddDate(0, -1, 0),
		BillingPeriodEnd:   dueDate,
		IssueDate:          dueDate.AddDate(0, 0, -30),
		DueDate:            dueDate,
		TotalAmount:        200_000,
		Status:             "unpaid",
		InvoiceType:        "recurring",
		IsAutoGenerated:    true,
	}
	require.NoError(t, repos.InvoiceRepo.Create(suite.Ctx, invoice))

	// Run overdue check (no-op for isolation since subscriptionSvc not set)
	err := billingSvc.CheckAndIsolateOverdue(suite.Ctx)
	require.NoError(t, err)

	// Simulate isolation (bypass router)
	subID, _ := uuid.Parse(sub.ID)
	directIsolate(t, suite, subID.String())

	updatedSub, err := repos.SubscriptionRepo.GetByID(suite.Ctx, subID)
	require.NoError(t, err)
	assert.Equal(t, "isolated", updatedSub.Status)
}
