package service

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
	billingDomain "mikmongo/internal/domain/billing"
	"mikmongo/internal/model"
	"mikmongo/internal/service/mocks"
)

// --- helpers ---

func newBillingServiceWithMocks() (
	*BillingService,
	*mocks.MockInvoiceRepository,
	*mocks.MockInvoiceItemRepository,
	*mocks.MockSubscriptionRepository,
	*mocks.MockBandwidthProfileRepository,
	*mocks.MockCustomerRepository,
	*mocks.MockSystemSettingRepository,
	*mocks.MockSequenceCounterRepository,
) {
	invoiceRepo := &mocks.MockInvoiceRepository{}
	itemRepo := &mocks.MockInvoiceItemRepository{}
	subRepo := &mocks.MockSubscriptionRepository{}
	profileRepo := &mocks.MockBandwidthProfileRepository{}
	customerRepo := &mocks.MockCustomerRepository{}
	settingRepo := &mocks.MockSystemSettingRepository{}
	seqRepo := &mocks.MockSequenceCounterRepository{}

	svc := NewBillingService(
		invoiceRepo,
		itemRepo,
		subRepo,
		profileRepo,
		customerRepo,
		settingRepo,
		seqRepo,
		billingDomain.NewDomain(),
	)
	return svc, invoiceRepo, itemRepo, subRepo, profileRepo, customerRepo, settingRepo, seqRepo
}

func setupSettingAndSeq(settingRepo *mocks.MockSystemSettingRepository, seqRepo *mocks.MockSequenceCounterRepository, invoiceNum int) {
	settingRepo.On("GetByGroupAndKey", mock.Anything, "billing", "due_days").
		Return(&model.SystemSetting{Value: strPtr("10")}, nil).Maybe()
	seqRepo.On("NextNumber", mock.Anything, "invoice_number").
		Return(invoiceNum, nil)
}

func strPtr(s string) *string { return &s }
func intPtr(i int) *int       { return &i }

// --- tests ---

func TestGenerateInvoice_NewSubscription(t *testing.T) {
	ctx := context.Background()
	svc, invoiceRepo, itemRepo, subRepo, profileRepo, customerRepo, settingRepo, seqRepo := newBillingServiceWithMocks()

	subID := uuid.New()
	customerID := uuid.New()
	planID := uuid.New()

	now := time.Date(2024, time.March, 1, 0, 0, 0, 0, time.Local)

	sub := &model.Subscription{
		ID:         subID.String(),
		CustomerID: customerID.String(),
		PlanID:     planID.String(),
		Status:     "active",
	}

	profile := &model.BandwidthProfile{
		ID:           planID.String(),
		Name:         "Paket 10Mbps",
		PriceMonthly: 200_000,
		TaxRate:      0.11,
		BillingDay:   intPtr(1),
	}

	customer := &model.Customer{ID: customerID.String(), FullName: "Budi", Phone: "081234"}

	setupSettingAndSeq(settingRepo, seqRepo, 1)
	subRepo.On("GetByID", ctx, subID).Return(sub, nil)
	profileRepo.On("GetByID", ctx, planID).Return(profile, nil)
	invoiceRepo.On("GetBySubscriptionAndPeriod", ctx, subID, mock.Anything, mock.Anything).Return(nil, fmt.Errorf("not found"))
	invoiceRepo.On("Create", ctx, mock.AnythingOfType("*model.Invoice")).Return(nil)
	itemRepo.On("Create", ctx, mock.AnythingOfType("*model.InvoiceItem")).Return(nil)
	customerRepo.On("GetByID", ctx, customerID).Return(customer, nil)

	inv, err := svc.GenerateInvoice(ctx, subID, now)
	require.NoError(t, err)
	assert.NotNil(t, inv)
	assert.Equal(t, "INV000001", inv.InvoiceNumber)
	assert.Equal(t, "unpaid", inv.Status)
	assert.Equal(t, "recurring", inv.InvoiceType)
	assert.True(t, inv.IsAutoGenerated)
	assert.Equal(t, profile.PriceMonthly, inv.Subtotal)
}

func TestGenerateInvoice_Proration(t *testing.T) {
	ctx := context.Background()
	svc, invoiceRepo, itemRepo, subRepo, profileRepo, customerRepo, settingRepo, seqRepo := newBillingServiceWithMocks()

	subID := uuid.New()
	customerID := uuid.New()
	planID := uuid.New()

	// Subscription activated on March 16
	activatedAt := time.Date(2024, time.March, 16, 0, 0, 0, 0, time.Local)
	billedPeriod := time.Date(2024, time.March, 1, 0, 0, 0, 0, time.Local)

	sub := &model.Subscription{
		ID:          subID.String(),
		CustomerID:  customerID.String(),
		PlanID:      planID.String(),
		Status:      "active",
		ActivatedAt: &activatedAt,
	}

	profile := &model.BandwidthProfile{
		ID:           planID.String(),
		Name:         "Paket 10Mbps",
		PriceMonthly: 310_000, // 31-day month: 10_000/day
		TaxRate:      0,
		BillingDay:   intPtr(1),
	}

	customer := &model.Customer{ID: customerID.String(), FullName: "Budi", Phone: "081234"}

	setupSettingAndSeq(settingRepo, seqRepo, 2)
	subRepo.On("GetByID", ctx, subID).Return(sub, nil)
	profileRepo.On("GetByID", ctx, planID).Return(profile, nil)
	invoiceRepo.On("GetBySubscriptionAndPeriod", ctx, subID, mock.Anything, mock.Anything).Return(nil, fmt.Errorf("not found"))
	invoiceRepo.On("Create", ctx, mock.AnythingOfType("*model.Invoice")).Return(nil)
	itemRepo.On("Create", ctx, mock.AnythingOfType("*model.InvoiceItem")).Return(nil)
	customerRepo.On("GetByID", ctx, customerID).Return(customer, nil)

	inv, err := svc.GenerateInvoice(ctx, subID, billedPeriod)
	require.NoError(t, err)

	// March has 31 days; activated day 16 → billedDays = 31 - 16 + 1 = 16
	// proration = 310_000 * 16/31 = 160_000
	expectedProration := billingDomain.NewDomain().CalculateProration(310_000, 31, 16)
	assert.Equal(t, expectedProration, inv.Subtotal)
	assert.Less(t, inv.Subtotal, profile.PriceMonthly)
}

func TestGenerateInvoice_SuspendedSubscription(t *testing.T) {
	ctx := context.Background()
	svc, _, _, subRepo, _, _, _, _ := newBillingServiceWithMocks()

	subID := uuid.New()
	sub := &model.Subscription{
		ID:     subID.String(),
		PlanID: uuid.New().String(),
		Status: "suspended",
	}
	subRepo.On("GetByID", ctx, subID).Return(sub, nil)

	_, err := svc.GenerateInvoice(ctx, subID, time.Now())
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "suspended")
}

func TestGenerateInvoice_WithTax(t *testing.T) {
	ctx := context.Background()
	svc, invoiceRepo, itemRepo, subRepo, profileRepo, customerRepo, settingRepo, seqRepo := newBillingServiceWithMocks()

	subID := uuid.New()
	customerID := uuid.New()
	planID := uuid.New()

	sub := &model.Subscription{
		ID:         subID.String(),
		CustomerID: customerID.String(),
		PlanID:     planID.String(),
		Status:     "active",
	}

	profile := &model.BandwidthProfile{
		ID:           planID.String(),
		Name:         "Paket 10Mbps",
		PriceMonthly: 100_000,
		TaxRate:      0.11,
		BillingDay:   intPtr(1),
	}

	customer := &model.Customer{ID: customerID.String(), FullName: "Budi", Phone: "081234"}

	setupSettingAndSeq(settingRepo, seqRepo, 3)
	subRepo.On("GetByID", ctx, subID).Return(sub, nil)
	profileRepo.On("GetByID", ctx, planID).Return(profile, nil)
	invoiceRepo.On("GetBySubscriptionAndPeriod", ctx, subID, mock.Anything, mock.Anything).Return(nil, fmt.Errorf("not found"))
	invoiceRepo.On("Create", ctx, mock.AnythingOfType("*model.Invoice")).Return(nil)
	itemRepo.On("Create", ctx, mock.AnythingOfType("*model.InvoiceItem")).Return(nil)
	customerRepo.On("GetByID", ctx, customerID).Return(customer, nil)

	inv, err := svc.GenerateInvoice(ctx, subID, time.Date(2024, time.March, 1, 0, 0, 0, 0, time.Local))
	require.NoError(t, err)
	assert.Equal(t, 11_000.0, inv.TaxAmount)
	assert.Equal(t, 111_000.0, inv.TotalAmount)
}

func TestProcessDailyBilling_BillingDayToday(t *testing.T) {
	ctx := context.Background()
	svc, invoiceRepo, itemRepo, subRepo, profileRepo, customerRepo, settingRepo, seqRepo := newBillingServiceWithMocks()

	today := time.Now().Day()
	subID := uuid.New()
	customerID := uuid.New()
	planID := uuid.New()

	sub := &model.Subscription{
		ID:         subID.String(),
		CustomerID: customerID.String(),
		PlanID:     planID.String(),
		Status:     "active",
		BillingDay: intPtr(today),
	}

	profile := &model.BandwidthProfile{
		ID:           planID.String(),
		Name:         "Paket 10Mbps",
		PriceMonthly: 200_000,
		TaxRate:      0.11,
		BillingDay:   intPtr(today),
	}
	customer := &model.Customer{ID: customerID.String(), FullName: "Budi", Phone: "081234", IsActive: true}

	subRepo.On("ListByStatus", ctx, "active").Return([]model.Subscription{*sub}, nil)
	subRepo.On("ListByStatus", ctx, "isolated").Return([]model.Subscription{}, nil)
	subRepo.On("GetByID", ctx, subID).Return(sub, nil)
	customerRepo.On("GetByID", ctx, customerID).Return(customer, nil)
	profileRepo.On("GetByID", ctx, planID).Return(profile, nil)
	settingRepo.On("GetByGroupAndKey", mock.Anything, "billing", "due_days").
		Return(&model.SystemSetting{Value: strPtr("10")}, nil)
	seqRepo.On("NextNumber", mock.Anything, "invoice_number").Return(10, nil)
	invoiceRepo.On("GetBySubscriptionAndPeriod", ctx, subID, mock.Anything, mock.Anything).Return(nil, fmt.Errorf("not found"))
	invoiceRepo.On("Create", ctx, mock.AnythingOfType("*model.Invoice")).Return(nil)
	itemRepo.On("Create", ctx, mock.AnythingOfType("*model.InvoiceItem")).Return(nil)

	err := svc.ProcessDailyBilling(ctx)
	assert.NoError(t, err)
	invoiceRepo.AssertCalled(t, "Create", ctx, mock.AnythingOfType("*model.Invoice"))
}

func TestProcessDailyBilling_DifferentBillingDay(t *testing.T) {
	ctx := context.Background()
	svc, invoiceRepo, _, subRepo, profileRepo, customerRepo, _, _ := newBillingServiceWithMocks()

	today := time.Now().Day()
	// Use a different billing day (not today)
	billingDay := today%28 + 1
	if billingDay == today {
		billingDay = (today % 27) + 2
	}

	subID := uuid.New()
	customerID := uuid.New()
	planID := uuid.New()

	sub := &model.Subscription{
		ID:         subID.String(),
		CustomerID: customerID.String(),
		PlanID:     planID.String(),
		Status:     "active",
		BillingDay: intPtr(billingDay),
	}
	profile := &model.BandwidthProfile{
		ID:           planID.String(),
		PriceMonthly: 200_000,
		TaxRate:      0,
		BillingDay:   intPtr(billingDay),
	}
	customer := &model.Customer{ID: customerID.String(), FullName: "Budi", Phone: "081234", IsActive: true}

	subRepo.On("ListByStatus", ctx, "active").Return([]model.Subscription{*sub}, nil)
	subRepo.On("ListByStatus", ctx, "isolated").Return([]model.Subscription{}, nil)
	customerRepo.On("GetByID", ctx, customerID).Return(customer, nil)
	profileRepo.On("GetByID", ctx, planID).Return(profile, nil)

	err := svc.ProcessDailyBilling(ctx)
	assert.NoError(t, err)
	invoiceRepo.AssertNotCalled(t, "Create", mock.Anything, mock.Anything)
}

func TestCheckAndIsolateOverdue_ShouldIsolate(t *testing.T) {
	ctx := context.Background()
	svc, _, _, subRepo, profileRepo, _, _, _ := newBillingServiceWithMocks()
	invoiceRepo := &mocks.MockInvoiceRepository{}
	svc.invoiceRepo = invoiceRepo

	subID := uuid.New()
	planID := uuid.New()
	subIDStr := subID.String()

	dueDate := time.Now().AddDate(0, 0, -10) // 10 days overdue
	inv := model.Invoice{
		ID:             uuid.New().String(),
		Status:         "unpaid",
		DueDate:        dueDate,
		SubscriptionID: &subIDStr,
	}

	sub := &model.Subscription{
		ID:          subID.String(),
		PlanID:      planID.String(),
		Status:      "active",
		AutoIsolate: true,
	}
	profile := &model.BandwidthProfile{
		ID:              planID.String(),
		GracePeriodDays: 3,
	}

	invoiceRepo.On("GetOverdue", ctx).Return([]model.Invoice{inv}, nil)
	subRepo.On("GetByID", ctx, subID).Return(sub, nil)
	profileRepo.On("GetByID", ctx, planID).Return(profile, nil)

	// No subscription service wired → just checks it doesn't crash
	err := svc.CheckAndIsolateOverdue(ctx)
	assert.NoError(t, err)
}

func TestCheckAndIsolateOverdue_WithinGracePeriod(t *testing.T) {
	ctx := context.Background()
	svc, _, _, subRepo, profileRepo, _, _, _ := newBillingServiceWithMocks()
	invoiceRepo := &mocks.MockInvoiceRepository{}
	svc.invoiceRepo = invoiceRepo

	subID := uuid.New()
	planID := uuid.New()
	subIDStr := subID.String()

	// Only 1 day overdue, grace = 3
	dueDate := time.Now().AddDate(0, 0, -1)
	inv := model.Invoice{
		ID:             uuid.New().String(),
		Status:         "unpaid",
		DueDate:        dueDate,
		SubscriptionID: &subIDStr,
	}

	sub := &model.Subscription{
		ID:          subID.String(),
		PlanID:      planID.String(),
		Status:      "active",
		AutoIsolate: true,
	}
	profile := &model.BandwidthProfile{
		ID:              planID.String(),
		GracePeriodDays: 3,
	}

	invoiceRepo.On("GetOverdue", ctx).Return([]model.Invoice{inv}, nil)
	subRepo.On("GetByID", ctx, subID).Return(sub, nil)
	profileRepo.On("GetByID", ctx, planID).Return(profile, nil)

	err := svc.CheckAndIsolateOverdue(ctx)
	assert.NoError(t, err)
	// subscriptionSvc is nil so Isolate() is never called; verify no panic
}

// ensure fmt is used
var _ = fmt.Sprintf
