package dto

import (
	"time"

	"mikmongo/internal/model"
)

// === RESPONSE ===

// InvoiceResponse is the safe response struct.
// InternalNotes, DeletedAt are excluded.
type InvoiceResponse struct {
	ID                 string     `json:"id"`
	InvoiceNumber      string     `json:"invoice_number"`
	CustomerID         string     `json:"customer_id"`
	SubscriptionID     *string    `json:"subscription_id,omitempty"`
	BillingPeriodStart time.Time  `json:"billing_period_start"`
	BillingPeriodEnd   time.Time  `json:"billing_period_end"`
	BillingMonth       *int       `json:"billing_month,omitempty"`
	BillingYear        *int       `json:"billing_year,omitempty"`
	IssueDate          time.Time  `json:"issue_date"`
	DueDate            time.Time  `json:"due_date"`
	PaymentDeadline    *time.Time `json:"payment_deadline,omitempty"`
	Subtotal           float64    `json:"subtotal"`
	TaxAmount          float64    `json:"tax_amount"`
	DiscountAmount     float64    `json:"discount_amount"`
	LateFee            float64    `json:"late_fee"`
	TotalAmount        float64    `json:"total_amount"`
	PaidAmount         float64    `json:"paid_amount"`
	Balance            float64    `json:"balance"`
	Status             string     `json:"status"`
	PaymentDate        *time.Time `json:"payment_date,omitempty"`
	PaymentMethod      *string    `json:"payment_method,omitempty"`
	InvoiceType        string     `json:"invoice_type"`
	IsAutoGenerated    bool       `json:"is_auto_generated"`
	Notes              *string    `json:"notes,omitempty"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
}

// === CONVERTERS ===

// InvoiceToResponse converts a model to a response DTO.
func InvoiceToResponse(m *model.Invoice) InvoiceResponse {
	return InvoiceResponse{
		ID:                 m.ID,
		InvoiceNumber:      m.InvoiceNumber,
		CustomerID:         m.CustomerID,
		SubscriptionID:     m.SubscriptionID,
		BillingPeriodStart: m.BillingPeriodStart,
		BillingPeriodEnd:   m.BillingPeriodEnd,
		BillingMonth:       m.BillingMonth,
		BillingYear:        m.BillingYear,
		IssueDate:          m.IssueDate,
		DueDate:            m.DueDate,
		PaymentDeadline:    m.PaymentDeadline,
		Subtotal:           m.Subtotal,
		TaxAmount:          m.TaxAmount,
		DiscountAmount:     m.DiscountAmount,
		LateFee:            m.LateFee,
		TotalAmount:        m.TotalAmount,
		PaidAmount:         m.PaidAmount,
		Balance:            m.Balance,
		Status:             m.Status,
		PaymentDate:        m.PaymentDate,
		PaymentMethod:      m.PaymentMethod,
		InvoiceType:        m.InvoiceType,
		IsAutoGenerated:    m.IsAutoGenerated,
		Notes:              m.Notes,
		CreatedAt:          m.CreatedAt,
		UpdatedAt:          m.UpdatedAt,
	}
}

// InvoicesToResponse converts a slice of models to response DTOs.
func InvoicesToResponse(ms []model.Invoice) []InvoiceResponse {
	result := make([]InvoiceResponse, len(ms))
	for i := range ms {
		result[i] = InvoiceToResponse(&ms[i])
	}
	return result
}
